### ISSUE TITLE
vs2015 binary

### ISSUE THREAD

**Issue by akirayu101** [webbju/android-plus-plus#1]
Would you please build a vs2015 version binary in android-plus-plus-master\bin\v14.0, thanks a lot

**Comment by voltagex** [comment]
Binaries shouldn't be in source control.

**Comment by oscarbg** [comment]
So can you publish a release with this binary?

**Comment by webbju** [comment]
2015 is still WIP, need to fix a few assembly issues as the VS 2015 SDK works a little differently.  Will try to do this as a matter of priority as it certainly comes across as 2015 is supported.  Hopefully it should be reasonably straight forward.

**Comment by webbju** [comment]
I'm conducting this work on the **vs-2015-support** branch.

https://github.com/webbju/android-plus-plus/tree/vs-2015-support

**Comment by webbju** [comment]
Branch reintegrated. 2015 should now be supported, please let me know if you have any problems.
